# Generated by Django 3.0.9 on 2020-09-12 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_follower_like_posts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['-date_time']},
        ),
    ]
